name: CI Frontend
on: 
  push:
    branches:
      - master
jobs:
  connectSsh:
    runs-on: ubuntu-18.04
    steps:
      - name: connect to ssh
        uses: appleboy/ssh-action@master
        with:
          host: '35.185.180.244'
          username: chicken
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            pwd
            ls -l
            whoami
