name: CI Frontend
on: 
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #???
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} #???

      - name: Build And Push Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: ./ # path đến folder chạy Docker Build, >> docker build -t ???
          file: ./Dockerfile
          push: true  #(sau khi build sẽ push Image)
          tags: huyth2403/hello-world