name: build-test
on: 
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Print Test
        run: echo pwd