name: CI FE
on: 
  push:
    branches: 
      - master
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Setup Docker BuildX
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        id: docker-build
        with:
          context: ./
          # builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world

      - name: Verify
        run: echo ${{ steps.docker-build.outputs.digest }}