name: CI Frontend
on: 
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: huyth2403
          password: 051c9bc6-4493-4a1d-b3e6-588fff623096
          
      - name: Build And Push Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: huyth2403/testttttt