name: CI Frontend
on: 
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and Build Prod
        run: npm install && npm run build
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:v1
      - name: connect to ssh
        uses: appleboy/ssh-action@master
        with:
          host: '35.185.180.244'
          username: chicken
          key: ${{ secrets.PRIVATE_KEY_1 }}
          port: 22
          script: sudo docker pull huyth2403/hello-world:v1 && sudo docker run --name frontend -it -dp 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:v1
